steps:
  - label: ':eslint: Lint'
    command: .buildkite/steps/lint.sh
    agents:
      queue: npm-packages
    env:
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: bundle_script_tag_plugin

  - wait

  - label: ':rocket: publish'
    command: .buildkite/steps/publish.sh
    agents:
      queue: npm-packages
    concurrency: 1
    concurrency_group: 'bundle-script-tag/publish'
    env:
      BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: bundle_script_tag_plugin

